### ISSUE TITLE
prox_eval of the L2_Norm_Squared is not corret.

### ISSUE THREAD

**Issue by wenh06** [unc-optimization/FedDR#1]
The `prox_eval` function of [`L2_Norm_Squared`](https://github.com/unc-optimization/FedDR/blob/main/FedDR/flearn/regularizers/l2_norm_squared.py). It is in fact the proximal of L2 norm rather than the L2 norm squared.

**Comment by nhanph** [comment]
Thank you for catching this. The issue has been fixed in [8cec928](https://github.com/unc-optimization/FedDR/commit/8cec92824adeab477931bbc60addcb48fdbe71ab).
