### ISSUE TITLE
AsyncFedDR

### ISSUE THREAD

**Issue by wyyhaha-rgb** [unc-optimization/FedDR#2]
Hello， I want to ask you about how asynchronous is implemented, I don't understand

**Comment by nhanph** [comment]
Hello,

Our asynchronous framework relies on the distbelief implementation [here](https://github.com/ucla-labx/distbelief). You can read more about the asynchronous implementation in this [blog post](https://jcaip.github.io/Distbelief/).

Similar to distbelief, we have a parameter server and worker communication. Our communication scheme can be described as follows:

**On the server side:**
- At the beginning, the server [sends](https://github.com/unc-optimization/FedDR/blob/4097eb447a99c7180388527a2d05974906b77eb1/AsyncFedDR/asyncfeddr/server.py#L178) the initial model to each worker. 
- After that, whenever the server [receives](https://github.com/unc-optimization/FedDR/blob/4097eb447a99c7180388527a2d05974906b77eb1/AsyncFedDR/asyncfeddr/server.py#L235) the local update from a worker, it performs server update then [send back](https://github.com/unc-optimization/FedDR/blob/4097eb447a99c7180388527a2d05974906b77eb1/AsyncFedDR/asyncfeddr/server.py#L251) the new model to that worker.

**On the worker side:**
- Whenever a worker [receives](https://github.com/unc-optimization/FedDR/blob/4097eb447a99c7180388527a2d05974906b77eb1/AsyncFedDR/asyncfeddr/worker.py#L64) the new model, it performs its local update.
- Then it [sends back](https://github.com/unc-optimization/FedDR/blob/4097eb447a99c7180388527a2d05974906b77eb1/AsyncFedDR/asyncfeddr/worker.py#L113) the updated local model to the server.

Let me know if you have any more questions.

**Comment by wyyhaha-rgb** [comment]
Thank you for your prompt reply.

**Comment by wyyhaha-rgb** [comment]
- I understand the process of federated learning, but in your code, I don't get the idea of asynchrony.

**Comment by nhanph** [comment]
closed issue for now, if you have more questions, feel free to reopen it.
